// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/creator/[tenantType]/[tenantId]" | "/creator/create-tenant" | "/site/[tenantId]" | "/site/[tenantId]/[pageSlug]" | "/site/[tenantId]/[pageSlug]/preview"
type AppRouteHandlerRoutes = "/api/content/snapshot" | "/api/create-tenant"
type PageRoutes = never
type LayoutRoutes = "/" | "/creator/[tenantType]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/content/snapshot": {}
  "/api/create-tenant": {}
  "/creator/[tenantType]": { "tenantType": string; }
  "/creator/[tenantType]/[tenantId]": { "tenantType": string; "tenantId": string; }
  "/creator/create-tenant": {}
  "/site/[tenantId]": { "tenantId": string; }
  "/site/[tenantId]/[pageSlug]": { "tenantId": string; "pageSlug": string; }
  "/site/[tenantId]/[pageSlug]/preview": { "tenantId": string; "pageSlug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/creator/[tenantType]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
